# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np
x = np.array( [1, 2, 3] )

In [2]:
x

array([1, 2, 3])

In [3]:
np.array?

In [15]:
b = np.arange(9, -1, -1)

In [18]:
b
type(b)

numpy.ndarray

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [26]:
np.diag(np.arange(5, -1, -1), k=0)

array([[5, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [27]:
matrix = np.diag(np.arange(5, -1, -1), k=0)

In [28]:
matrix.sum()

15

# Задание 3
Решите систему уравнений:
4x + 2y + z = 4;
x + 3y = 12;
5y + 4z = -3;

In [33]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [ 4, 12, -3] )

In [34]:
from numpy import linalg

In [35]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [36]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True